### ISSUE TITLE
Implement preview

### ISSUE THREAD

**Issue by electr0sheep** [catskull/GB-Logo-Generator#3]

**Comment by catskull** [comment]
Create an image (probably bitmap) from the hex data and show a little preview of what it will look like on a gameboy. It should have the logo text as well as the ®. It should scroll down and maybe even play the ding sound.

**Comment by electr0sheep** [comment]
I'm not sure how to approach this. Possibly get an image of a gameboy with a drawable layer where the screen should be?

**Comment by catskull** [comment]
I probably wouldn't worry about doing this.
