### ISSUE TITLE
Doesn't work in IE or Safari

### ISSUE THREAD

**Issue by electr0sheep** [catskull/GB-Logo-Generator#31]
Not even sure if we should care...both the browsers are trash anyway.

If we do care, I'm really not sure how to approach it, I don't think Safari allows downloads using anchors (because why not?). And what works with IE 8 doesn't work with IE 9 and what works with that doesn't work with IE 11 (because how do you program again?)

**Comment by catskull** [comment]
No, this is not necessary.
