### ISSUE TITLE
Look into making an .ips patch

### ISSUE THREAD

**Issue by catskull** [catskull/GB-Logo-Generator#6]
.ips files are designed to patch roms with new data, commonly used in rom translations. Look into creating an .ips patch so the logo could be patched onto any existing rom. This is low priority since this would make the rom not bootable.

**Comment by electr0sheep** [comment]
Didn't you say something about some rip-off Chinese companies using their own boot logo, then swapping the last frame with the correct logo?

EDIT: nvm, you can find out all about headers [here](http://gbdev.gg8.se/wiki/articles/The_Cartridge_Header)

**Comment by catskull** [comment]
I don't think this is feasible without some special cartridge hardware. Closing for now.
